### PR TITLE
adding mqtt ssl support

### PR DESCRIPTION
**Pull request by lefty01**
hi,
I created two branches in my fork one is this one about adding tls/ssl support for mqtt connections.
it's a bit 'messed' (aka cleaned-up) by atom (whitespace) wasn't intended.
also I point to my fork of the matrix dma lib and using mqtt with ssl is the default here ... so might need cleanup before merging ... IF you find it useful  ;)

### CODE REVIEW

**Comment by bogd** [comment]
Thank you! I will take a look, and merge if possible.

My concern here is the use of the forked matrix lib - I would (of course) prefer to keep using the original lib. Is there any reason why this would require your fork?

**Comment by lefty01** [comment]
a valid concern, as mentioned that would need cleanup. main reason was that I configured my matrix panel in the matrix lib headers.
I think I push an update to the branch later and restore the ini file

**Comment by bogd** [comment]
A big thank you for sharing, and a big apology for the delay - with this being a hobby project, real life got in the way, and I posponed this for far too long...

**Comment by lefty01** [comment]
cool! ... meanwhile the fork has further diverged. some important changes include platformio.ini, split config into config64x64 and 64x128 (I use only a 64x64 panel), query weather info from openweather (not perfect but it works). and can send msg via mtqq to the notification area.
so if you are interested feel free to copy code are ask about it ... maybe we can further share some of the coding ;)
I like your code, this way I learned more about platform.io and ESP32httpUpdate which I had not used before.
one of the things I would like to look into next is scrolling text in the message area (in case of longer msg)

**Comment by bogd** [comment]
Thank you - I already started going through your weather code, and I will try to implement something similar (with some changes, since in my case I use accuweather for... historical reasons :) ). I will credit any code that I use, of course :)

I have also added a watchdog to reset the unit if something goes wrong - in the last few months, I had several occurrences of the main thread hanging (the clock still works, but nothins else gets updated). My best guess is that it gets stuck somewhere when reading the light sensor - but I have found no way to avoid that. So for now, I will just reboot the ESP automatically if this happens.

As for the other changes (MQTT notifications, scrolling, etc), they were also planned for my implementation. Hopefully I will be able to get them implemented as well :)

**Pull request merged**
